# Generated by Django 5.0.6 on 2024-06-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamCollabAPI', '0002_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
    ]
